---
title: "resume"
author: "Renee Wang UNI:hw2851"
date: "11/6/2021"
output: html_document
---

# Hongrui Wang

## EDUCATION

* Columbia University, Sep. 2021 - May 2022(expected)
  - Master of Science in Biostatistics
  - Related Course: Probability, Data Science, Biostatistical Method, Introduction of epidemiology

* Stony Brook University, Sep. 2017 – Dec. 2020
  - Bachelor of Science in Biochemistry	Stony Brook, NY
  - Overall GPA: 3.18
  - Related Course: Biochemistry, Physical Chemistry, Cell biology, Calculus, Python, Statistics, Molecular Biology, General Chemistry, Organic Chemistry, Cellular and Organ Physiology, Public Speaking
  - Selected Honors: Dean’s list (Fall 2017, Fall 2018, Spring 2020 & Fall 2020)

* Wheelock College, Sep. 2016 – Jun. 2017
  - Overall GPA: 3.88	Boston, MA
  - Selected Honors: Dean’s list (Fall 2016)

## WORK EXPERIENCE

* Hansoh Pharmaceutical Company, May – Aug. 2018, Summer Internship Program
  - Rotated through different departments to learn the operation of the company
  - Collaborated with HR director to organize and provide support for candidate interviews
  - Organized files related to marketing strategy for new drugs and participated in related meetings


